version: '2.1'
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: 10m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030"]
      interval: 10s
      timeout: 10s
      retries: 3
    #ports:
    #  - '3030:3030'
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: 10m
    environment:
     - MESSAGE=${CUSTOM_MESSAGE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 10s
      retries: 3
    #ports:
    #  - '3000:3000'
  nginx:
    image: nginx
    container_name: "nginx"
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: 10m
    

